### ISSUE TITLE
the example chart should focus only on ties/#2 temps from ~2015 ideally

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/weather-temps#114]
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/2880174/169104369-5f094efb-abbd-4034-a0f1-5b59178c5ad4.png">

**Comment by russellgoldenberg** [comment]
got it, so adding logic to look for the most recent #2 first. what takes precedence, more recent year or #2 vs. tie?

**Comment by matthewfdaniels** [comment]
order of priority:
using past 5 records...
1. most recent #2 in past 10 years
2. tie in past 10 years
3. not sure what to do if neither doesn't exist...potentially add in more than past 5 records to extend out 10 years...
