### ISSUE TITLE
underline missing in last letters of byline (obvs small fry stuff)

### ISSUE THREAD

**Issue by iblind** [the-pudding/weather-temps#140]
![image](https://user-images.githubusercontent.com/7697604/169888990-ee90360b-379d-4fd5-9b8e-1c32f133225d.png)

**Comment by russellgoldenberg** [comment]
ah that is just how the font handles underlines, its a style (the last letters happen to be the only ones that dip below baseline)

**Comment by iblind** [comment]
🫡🫡
