### ISSUE TITLE
screen is still showing too old of a record. 

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/weather-temps#141]
this should only show a year that’s in the recent past (40 years back is too far)

**Comment by matthewfdaniels** [comment]
![Uploading B8205533-5D94-4542-A9CA-F5C121CFA27D.png…]()

**Comment by russellgoldenberg** [comment]
can't see the screenshot, but assuming NY that is the most recent record from the top 5... so unless we change up the viz on the previous slide to show more than 5, we are stuck wit that
