### ISSUE TITLE
adjust shadow on text

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/weather-temps#46]
<img width="121" alt="image" src="https://user-images.githubusercontent.com/2880174/167500396-52934d14-3a8b-455c-8a77-e2e54d9a2a9f.png">

**Comment by russellgoldenberg** [comment]
this is taken verbatim from the nyt article you sent, you can adjust [here](https://github.com/the-pudding/weather-temps/blob/main/src/styles/app.css#L78)
