### ISSUE TITLE
should we adjust y-axis on these screens to be min/max of date???

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/weather-temps#51]
<img width="202" alt="image" src="https://user-images.githubusercontent.com/2880174/167501231-05b9cc7e-f4c8-400f-9ce7-c0956088ea68.png">

**Comment by russellgoldenberg** [comment]
i think this adds a level of motion/changing that doesn't add much (i experiment with this initially). i think it is better to ground the y axis in a constant temp range so the only thing changing is the time.
