### ISSUE TITLE
remove the x-axis bar?

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/weather-temps#98]

**Comment by russellgoldenberg** [comment]
this was already removed.

**Comment by matthewfdaniels** [comment]
oh i mean i was thinking it should be there. were you keen on removing it? I have it in my figma files but down to discuss it.

**Comment by russellgoldenberg** [comment]
doesn't really make sense to me since it is not a baseline anymore without it being 0, since things will go below it, seems arbitrary to have 1 and not all.

**Comment by matthewfdaniels** [comment]
if that's the case then the x-axis labels can definitely hug the chart way more i think
